<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['name' => '25 De Mayo', 'province_id' => '1'],
            ['name' => '9 De Julio', 'province_id' => '1'],
            ['name' => 'Adolfo Alsina', 'province_id' => '1'],
            ['name' => 'Adolfo Gonzales Chaves', 'province_id' => '1'],
            ['name' => 'Alberti', 'province_id' => '1'],
            ['name' => 'Almirante Brown', 'province_id' => '1'],
            ['name' => 'Avellaneda', 'province_id' => '1'],
            ['name' => 'Ayacucho', 'province_id' => '1'],
            ['name' => 'Azul', 'province_id' => '1'],
            ['name' => 'Bahia Blanca', 'province_id' => '1'],
            ['name' => 'Balcarce', 'province_id' => '1'],
            ['name' => 'Baradero', 'province_id' => '1'],
            ['name' => 'Bartolome Mitre', 'province_id' => '1'],
            ['name' => 'Benito Juarez', 'province_id' => '1'],
            ['name' => 'Berazategui', 'province_id' => '1'],
            ['name' => 'Berisso', 'province_id' => '1'],
            ['name' => 'Bolivar', 'province_id' => '1'],
            ['name' => 'Bragado', 'province_id' => '1'],
            ['name' => 'Campana', 'province_id' => '1'],
            ['name' => 'Capitan Sarmiento', 'province_id' => '1'],
            ['name' => 'Carlos Casares', 'province_id' => '1'],
            ['name' => 'Carlos Tejedor', 'province_id' => '1'],
            ['name' => 'Carmen De Areco', 'province_id' => '1'],
            ['name' => 'Castelli', 'province_id' => '1'],
            ['name' => 'Chacabuco', 'province_id' => '1'],
            ['name' => 'Chascomus', 'province_id' => '1'],
            ['name' => 'Chivilcoy', 'province_id' => '1'],
            ['name' => 'Colon', 'province_id' => '1'],
            ['name' => 'Coronel Brandsen', 'province_id' => '1'],
            ['name' => 'Coronel Dorrego', 'province_id' => '1'],
            ['name' => 'Coronel Pringles', 'province_id' => '1'],
            ['name' => 'Coronel Rosales', 'province_id' => '1'],
            ['name' => 'Coronel Suarez', 'province_id' => '1'],
            ['name' => 'Daireaux', 'province_id' => '1'],
            ['name' => 'De La Costa', 'province_id' => '1'],
            ['name' => 'Dolores', 'province_id' => '1'],
            ['name' => 'Ensenada', 'province_id' => '1'],
            ['name' => 'Escobar', 'province_id' => '1'],
            ['name' => 'Esteban Echeverria', 'province_id' => '1'],
            ['name' => 'Exaltacion De La Cruz', 'province_id' => '1'],
            ['name' => 'Ezeiza', 'province_id' => '1'],
            ['name' => 'Florencio Varela', 'province_id' => '1'],
            ['name' => 'Florentino Ameghino', 'province_id' => '1'],
            ['name' => 'General Alvarado', 'province_id' => '1'],
            ['name' => 'General Alvear', 'province_id' => '1'],
            ['name' => 'General Arenales', 'province_id' => '1'],
            ['name' => 'General Belgrano', 'province_id' => '1'],
            ['name' => 'General Guido', 'province_id' => '1'],
            ['name' => 'General Lamadrid', 'province_id' => '1'],
            ['name' => 'General Las Heras', 'province_id' => '1'],
            ['name' => 'General Lavalle', 'province_id' => '1'],
            ['name' => 'General Madariaga', 'province_id' => '1'],
            ['name' => 'General Paz', 'province_id' => '1'],
            ['name' => 'General Pinto', 'province_id' => '1'],
            ['name' => 'General Pueyrredon', 'province_id' => '1'],
            ['name' => 'General Rodriguez', 'province_id' => '1'],
            ['name' => 'General San Martin', 'province_id' => '1'],
            ['name' => 'General Viamonte', 'province_id' => '1'],
            ['name' => 'General Villegas', 'province_id' => '1'],
            ['name' => 'Guamini', 'province_id' => '1'],
            ['name' => 'Hipolito Yrigoyen', 'province_id' => '1'],
            ['name' => 'Hurlingham', 'province_id' => '1'],
            ['name' => 'Ituzaingo', 'province_id' => '1'],
            ['name' => 'Jose Clemente Paz', 'province_id' => '1'],
            ['name' => 'Junin', 'province_id' => '1'],
            ['name' => 'La Matanza', 'province_id' => '1'],
            ['name' => 'La Plata', 'province_id' => '1'],
            ['name' => 'Lanus', 'province_id' => '1'],
            ['name' => 'Laprida', 'province_id' => '1'],
            ['name' => 'Las Flores', 'province_id' => '1'],
            ['name' => 'Leandro N Alem', 'province_id' => '1'],
            ['name' => 'Lincoln', 'province_id' => '1'],
            ['name' => 'Loberia', 'province_id' => '1'],
            ['name' => 'Lobos', 'province_id' => '1'],
            ['name' => 'Lomas De Zamora', 'province_id' => '1'],
            ['name' => 'Lujan', 'province_id' => '1'],
            ['name' => 'Magdalena', 'province_id' => '1'],
            ['name' => 'Maipu', 'province_id' => '1'],
            ['name' => 'Malvinas Argentinas', 'province_id' => '1'],
            ['name' => 'Mar Chiquita', 'province_id' => '1'],
            ['name' => 'Marcos Paz', 'province_id' => '1'],
            ['name' => 'Mercedes', 'province_id' => '1'],
            ['name' => 'Merlo', 'province_id' => '1'],
            ['name' => 'Monte', 'province_id' => '1'],
            ['name' => 'Monte Hermoso', 'province_id' => '1'],
            ['name' => 'Moreno', 'province_id' => '1'],
            ['name' => 'Moron', 'province_id' => '1'],
            ['name' => 'Navarro', 'province_id' => '1'],
            ['name' => 'Necochea', 'province_id' => '1'],
            ['name' => 'Olavarria', 'province_id' => '1'],
            ['name' => 'Patagones', 'province_id' => '1'],
            ['name' => 'Pehuajo', 'province_id' => '1'],
            ['name' => 'Pellegrini', 'province_id' => '1'],
            ['name' => 'Pergamino', 'province_id' => '1'],
            ['name' => 'Pila', 'province_id' => '1'],
            ['name' => 'Pilar', 'province_id' => '1'],
            ['name' => 'Pinamar', 'province_id' => '1'],
            ['name' => 'Presidente Peron', 'province_id' => '1'],
            ['name' => 'Puan', 'province_id' => '1'],
            ['name' => 'Punta Indio', 'province_id' => '1'],
            ['name' => 'Quilmes', 'province_id' => '1'],
            ['name' => 'Ramallo', 'province_id' => '1'],
            ['name' => 'Rauch', 'province_id' => '1'],
            ['name' => 'Rivadavia', 'province_id' => '1'],
            ['name' => 'Rojas', 'province_id' => '1'],
            ['name' => 'Roque Perez', 'province_id' => '1'],
            ['name' => 'Saavedra', 'province_id' => '1'],
            ['name' => 'Saladillo', 'province_id' => '1'],
            ['name' => 'Salliquelo', 'province_id' => '1'],
            ['name' => 'Salto', 'province_id' => '1'],
            ['name' => 'San Andres De Giles', 'province_id' => '1'],
            ['name' => 'San Antonio De Areco', 'province_id' => '1'],
            ['name' => 'San Cayetano', 'province_id' => '1'],
            ['name' => 'San Fernando', 'province_id' => '1'],
            ['name' => 'San Isidro', 'province_id' => '1'],
            ['name' => 'San Miguel', 'province_id' => '1'],
            ['name' => 'San Nicolas', 'province_id' => '1'],
            ['name' => 'San Pedro', 'province_id' => '1'],
            ['name' => 'San Vicente', 'province_id' => '1'],
            ['name' => 'Suipacha', 'province_id' => '1'],
            ['name' => 'Tandil', 'province_id' => '1'],
            ['name' => 'Tapalque', 'province_id' => '1'],
            ['name' => 'Tigre', 'province_id' => '1'],
            ['name' => 'Tordillo', 'province_id' => '1'],
            ['name' => 'Tornquist', 'province_id' => '1'],
            ['name' => 'Trenque Lauquen', 'province_id' => '1'],
            ['name' => 'Tres Arroyos', 'province_id' => '1'],
            ['name' => 'Tres De Febrero', 'province_id' => '1'],
            ['name' => 'Tres Lomas', 'province_id' => '1'],
            ['name' => 'Vicente Lopez', 'province_id' => '1'],
            ['name' => 'Villa Gesell', 'province_id' => '1'],
            ['name' => 'Villarino', 'province_id' => '1'],
            ['name' => 'Zarate', 'province_id' => '1'],
            ['name' => 'Capital Federal', 'province_id' => '2'],
            ['name' => 'Ambato', 'province_id' => '3'],
            ['name' => 'Ancasti', 'province_id' => '3'],
            ['name' => 'Andalgala', 'province_id' => '3'],
            ['name' => 'Antofagasta De La Sierra', 'province_id' => '3'],
            ['name' => 'Belen', 'province_id' => '3'],
            ['name' => 'Capayan', 'province_id' => '3'],
            ['name' => 'Capital', 'province_id' => '3'],
            ['name' => 'El Alto', 'province_id' => '3'],
            ['name' => 'Fray Mamerto Esquiu', 'province_id' => '3'],
            ['name' => 'La Paz', 'province_id' => '3'],
            ['name' => 'Paclin', 'province_id' => '3'],
            ['name' => 'Poman', 'province_id' => '3'],
            ['name' => 'Santa Maria', 'province_id' => '3'],
            ['name' => 'Santa Rosa', 'province_id' => '3'],
            ['name' => 'Tinogasta', 'province_id' => '3'],
            ['name' => 'Valle Viejo', 'province_id' => '3'],
            ['name' => '1 De Mayo', 'province_id' => '4'],
            ['name' => '12 De Octubre', 'province_id' => '4'],
            ['name' => '25 De Mayo', 'province_id' => '4'],
            ['name' => '9 De Julio', 'province_id' => '4'],
            ['name' => 'Almirante Brown', 'province_id' => '4'],
            ['name' => 'Bermejo', 'province_id' => '4'],
            ['name' => 'Chacabuco', 'province_id' => '4'],
            ['name' => 'Comandante Fernandez', 'province_id' => '4'],
            ['name' => 'Fray Justo Santa Maria De Oro', 'province_id' => '4'],
            ['name' => 'General Belgrano', 'province_id' => '4'],
            ['name' => 'General Donovan', 'province_id' => '4'],
            ['name' => 'General Guemes', 'province_id' => '4'],
            ['name' => 'Independencia', 'province_id' => '4'],
            ['name' => 'Libertad', 'province_id' => '4'],
            ['name' => 'Libertador Gral San Martin', 'province_id' => '4'],
            ['name' => 'Maipu', 'province_id' => '4'],
            ['name' => 'Mayor Luis J Fontana', 'province_id' => '4'],
            ['name' => 'O Higgins', 'province_id' => '4'],
            ['name' => 'Presidente De La Plaza', 'province_id' => '4'],
            ['name' => 'Quitilipi', 'province_id' => '4'],
            ['name' => 'San Fernando', 'province_id' => '4'],
            ['name' => 'San Lorenzo', 'province_id' => '4'],
            ['name' => 'Sargento Cabral', 'province_id' => '4'],
            ['name' => 'Tapenaga', 'province_id' => '4'],
            ['name' => 'Biedma', 'province_id' => '5'],
            ['name' => 'Cushamen', 'province_id' => '5'],
            ['name' => 'Escalante', 'province_id' => '5'],
            ['name' => 'Florentino Ameghino', 'province_id' => '5'],
            ['name' => 'Futaleufu', 'province_id' => '5'],
            ['name' => 'Gaiman', 'province_id' => '5'],
            ['name' => 'Gastre', 'province_id' => '5'],
            ['name' => 'Martires', 'province_id' => '5'],
            ['name' => 'Paso De Indios', 'province_id' => '5'],
            ['name' => 'Rawson', 'province_id' => '5'],
            ['name' => 'Rio Senguer', 'province_id' => '5'],
            ['name' => 'Sarmiento', 'province_id' => '5'],
            ['name' => 'Tehuelches', 'province_id' => '5'],
            ['name' => 'Telsen', 'province_id' => '5'],
            ['name' => 'Calamuchita', 'province_id' => '6'],
            ['name' => 'Capital', 'province_id' => '6'],
            ['name' => 'Colon', 'province_id' => '6'],
            ['name' => 'Cruz Del Eje', 'province_id' => '6'],
            ['name' => 'General Roca', 'province_id' => '6'],
            ['name' => 'General San Martin', 'province_id' => '6'],
            ['name' => 'Ischilin', 'province_id' => '6'],
            ['name' => 'Juarez Celman', 'province_id' => '6'],
            ['name' => 'Marcos Juarez', 'province_id' => '6'],
            ['name' => 'Minas', 'province_id' => '6'],
            ['name' => 'Pocho', 'province_id' => '6'],
            ['name' => 'Punilla', 'province_id' => '6'],
            ['name' => 'Rio Cuarto', 'province_id' => '6'],
            ['name' => 'Rio Primero', 'province_id' => '6'],
            ['name' => 'Rio Seco', 'province_id' => '6'],
            ['name' => 'Rio Segundo', 'province_id' => '6'],
            ['name' => 'San Alberto', 'province_id' => '6'],
            ['name' => 'San Javier', 'province_id' => '6'],
            ['name' => 'San Justo', 'province_id' => '6'],
            ['name' => 'Santa Maria', 'province_id' => '6'],
            ['name' => 'Sobremonte', 'province_id' => '6'],
            ['name' => 'Tercero Arriba', 'province_id' => '6'],
            ['name' => 'Totoral', 'province_id' => '6'],
            ['name' => 'Tulumba', 'province_id' => '6'],
            ['name' => 'Union', 'province_id' => '6'],
            ['name' => 'Bella Vista', 'province_id' => '7'],
            ['name' => 'Beron De Astrada', 'province_id' => '7'],
            ['name' => 'Capital', 'province_id' => '7'],
            ['name' => 'Concepcion', 'province_id' => '7'],
            ['name' => 'Curuzu Cuatia', 'province_id' => '7'],
            ['name' => 'Empedrado', 'province_id' => '7'],
            ['name' => 'Esquina', 'province_id' => '7'],
            ['name' => 'General Alvear', 'province_id' => '7'],
            ['name' => 'General Paz', 'province_id' => '7'],
            ['name' => 'Goya', 'province_id' => '7'],
            ['name' => 'Itati', 'province_id' => '7'],
            ['name' => 'Ituzaingo', 'province_id' => '7'],
            ['name' => 'Lavalle', 'province_id' => '7'],
            ['name' => 'Mburucuya', 'province_id' => '7'],
            ['name' => 'Mercedes', 'province_id' => '7'],
            ['name' => 'Monte Caseros', 'province_id' => '7'],
            ['name' => 'Paso De Los Libres', 'province_id' => '7'],
            ['name' => 'Saladas', 'province_id' => '7'],
            ['name' => 'San Cosme', 'province_id' => '7'],
            ['name' => 'San Luis Del Palmar', 'province_id' => '7'],
            ['name' => 'San Martin', 'province_id' => '7'],
            ['name' => 'San Miguel', 'province_id' => '7'],
            ['name' => 'San Roque', 'province_id' => '7'],
            ['name' => 'Santo Tome', 'province_id' => '7'],
            ['name' => 'Sauce', 'province_id' => '7'],
            ['name' => 'Colon', 'province_id' => '8'],
            ['name' => 'Concordia', 'province_id' => '8'],
            ['name' => 'Diamante', 'province_id' => '8'],
            ['name' => 'Federacion', 'province_id' => '8'],
            ['name' => 'Federal', 'province_id' => '8'],
            ['name' => 'Feliciano', 'province_id' => '8'],
            ['name' => 'Gualeguay', 'province_id' => '8'],
            ['name' => 'Gualeguaychu', 'province_id' => '8'],
            ['name' => 'Islas Del Ibicuy', 'province_id' => '8'],
            ['name' => 'La Paz', 'province_id' => '8'],
            ['name' => 'Nogoya', 'province_id' => '8'],
            ['name' => 'Parana', 'province_id' => '8'],
            ['name' => 'Tala', 'province_id' => '8'],
            ['name' => 'Uruguay', 'province_id' => '8'],
            ['name' => 'Victoria', 'province_id' => '8'],
            ['name' => 'Villaguay', 'province_id' => '8'],
            ['name' => 'Bermejo', 'province_id' => '9'],
            ['name' => 'Formosa', 'province_id' => '9'],
            ['name' => 'Laishi', 'province_id' => '9'],
            ['name' => 'Matacos', 'province_id' => '9'],
            ['name' => 'Pilagas', 'province_id' => '9'],
            ['name' => 'Pilcomayo', 'province_id' => '9'],
            ['name' => 'Pirane', 'province_id' => '9'],
            ['name' => 'Ramon Lista', 'province_id' => '9'],
            ['name' => 'Cochinoca', 'province_id' => '10'],
            ['name' => 'Dr Manuel Belgrano', 'province_id' => '10'],
            ['name' => 'El Carmen', 'province_id' => '10'],
            ['name' => 'Humahuaca', 'province_id' => '10'],
            ['name' => 'Ledesma', 'province_id' => '10'],
            ['name' => 'Palpala', 'province_id' => '10'],
            ['name' => 'Rinconada', 'province_id' => '10'],
            ['name' => 'San Antonio', 'province_id' => '10'],
            ['name' => 'San Pedro', 'province_id' => '10'],
            ['name' => 'Santa Barbara', 'province_id' => '10'],
            ['name' => 'Santa Catalina', 'province_id' => '10'],
            ['name' => 'Susques', 'province_id' => '10'],
            ['name' => 'Tilcara', 'province_id' => '10'],
            ['name' => 'Tumbaya', 'province_id' => '10'],
            ['name' => 'Valle Grande', 'province_id' => '10'],
            ['name' => 'Yavi', 'province_id' => '10'],
            ['name' => 'Atreuco', 'province_id' => '11'],
            ['name' => 'Caleu Caleu', 'province_id' => '11'],
            ['name' => 'Capital', 'province_id' => '11'],
            ['name' => 'Catrilo', 'province_id' => '11'],
            ['name' => 'Chalileo', 'province_id' => '11'],
            ['name' => 'Chapaleufu', 'province_id' => '11'],
            ['name' => 'Chical Co', 'province_id' => '11'],
            ['name' => 'Conhelo', 'province_id' => '11'],
            ['name' => 'Curaco', 'province_id' => '11'],
            ['name' => 'Guatrache', 'province_id' => '11'],
            ['name' => 'Hucal', 'province_id' => '11'],
            ['name' => 'Lihuel Calel', 'province_id' => '11'],
            ['name' => 'Limay Mahuida', 'province_id' => '11'],
            ['name' => 'Loventue', 'province_id' => '11'],
            ['name' => 'Maraco', 'province_id' => '11'],
            ['name' => 'Puelen', 'province_id' => '11'],
            ['name' => 'Quemu Quemu', 'province_id' => '11'],
            ['name' => 'Rancul', 'province_id' => '11'],
            ['name' => 'Realico', 'province_id' => '11'],
            ['name' => 'Toay', 'province_id' => '11'],
            ['name' => 'Trenel', 'province_id' => '11'],
            ['name' => 'Utracan', 'province_id' => '11'],
            ['name' => 'Arauco', 'province_id' => '12'],
            ['name' => 'Capital', 'province_id' => '12'],
            ['name' => 'Castro Barros', 'province_id' => '12'],
            ['name' => 'Chamical', 'province_id' => '12'],
            ['name' => 'Chilecito', 'province_id' => '12'],
            ['name' => 'Coronel Felipe Varela', 'province_id' => '12'],
            ['name' => 'Famatina', 'province_id' => '12'],
            ['name' => 'General Belgrano', 'province_id' => '12'],
            ['name' => 'General Juan Facundo Quiroga', 'province_id' => '12'],
            ['name' => 'General Lamadrid', 'province_id' => '12'],
            ['name' => 'General Ocampo', 'province_id' => '12'],
            ['name' => 'General San Martin', 'province_id' => '12'],
            ['name' => 'General Sarmiento', 'province_id' => '12'],
            ['name' => 'Gobernador Gordillo', 'province_id' => '12'],
            ['name' => 'Independencia', 'province_id' => '12'],
            ['name' => 'San Blas De Los Sauces', 'province_id' => '12'],
            ['name' => 'Sanagasta', 'province_id' => '12'],
            ['name' => 'Vinchina', 'province_id' => '12'],
            ['name' => 'Capital', 'province_id' => '13'],
            ['name' => 'General Alvear', 'province_id' => '13'],
            ['name' => 'Godoy Cruz', 'province_id' => '13'],
            ['name' => 'Guaymallen', 'province_id' => '13'],
            ['name' => 'Junin', 'province_id' => '13'],
            ['name' => 'La Paz', 'province_id' => '13'],
            ['name' => 'Las Heras', 'province_id' => '13'],
            ['name' => 'Lavalle', 'province_id' => '13'],
            ['name' => 'Lujan De Cuyo', 'province_id' => '13'],
            ['name' => 'Maipu', 'province_id' => '13'],
            ['name' => 'Malargue', 'province_id' => '13'],
            ['name' => 'Rivadavia', 'province_id' => '13'],
            ['name' => 'San Carlos', 'province_id' => '13'],
            ['name' => 'San Martin', 'province_id' => '13'],
            ['name' => 'San Rafael', 'province_id' => '13'],
            ['name' => 'Santa Rosa', 'province_id' => '13'],
            ['name' => 'Tunuyan', 'province_id' => '13'],
            ['name' => 'Tupungato', 'province_id' => '13'],
            ['name' => '25 De Mayo', 'province_id' => '14'],
            ['name' => 'Apostoles', 'province_id' => '14'],
            ['name' => 'Cainguas', 'province_id' => '14'],
            ['name' => 'Candelaria', 'province_id' => '14'],
            ['name' => 'Capital', 'province_id' => '14'],
            ['name' => 'Concepcion', 'province_id' => '14'],
            ['name' => 'El Dorado', 'province_id' => '14'],
            ['name' => 'General Manuel Belgrano', 'province_id' => '14'],
            ['name' => 'Guarani', 'province_id' => '14'],
            ['name' => 'Iguazu', 'province_id' => '14'],
            ['name' => 'Leandro N Alem', 'province_id' => '14'],
            ['name' => 'Libertador Gral San Martin', 'province_id' => '14'],
            ['name' => 'Montecarlo', 'province_id' => '14'],
            ['name' => 'Obera', 'province_id' => '14'],
            ['name' => 'San Ignacio', 'province_id' => '14'],
            ['name' => 'San Javier', 'province_id' => '14'],
            ['name' => 'San Pedro', 'province_id' => '14'],
            ['name' => 'Alumine', 'province_id' => '15'],
            ['name' => 'Catan Lil', 'province_id' => '15'],
            ['name' => 'Chos Malal', 'province_id' => '15'],
            ['name' => 'Collon Cura', 'province_id' => '15'],
            ['name' => 'Confluencia', 'province_id' => '15'],
            ['name' => 'Huiliches', 'province_id' => '15'],
            ['name' => 'Lacar', 'province_id' => '15'],
            ['name' => 'Loncopue', 'province_id' => '15'],
            ['name' => 'Los Lagos', 'province_id' => '15'],
            ['name' => 'Minas', 'province_id' => '15'],
            ['name' => 'Pehuenches', 'province_id' => '15'],
            ['name' => 'Picun Leufu', 'province_id' => '15'],
            ['name' => 'Picunches', 'province_id' => '15'],
            ['name' => 'Zapala', 'province_id' => '15'],
            ['name' => '25 De Mayo', 'province_id' => '16'],
            ['name' => '9 De Julio', 'province_id' => '16'],
            ['name' => 'Adolfo Alsina', 'province_id' => '16'],
            ['name' => 'Avellaneda', 'province_id' => '16'],
            ['name' => 'Bariloche', 'province_id' => '16'],
            ['name' => 'Conesa', 'province_id' => '16'],
            ['name' => 'El Cuy', 'province_id' => '16'],
            ['name' => 'General Roca', 'province_id' => '16'],
            ['name' => 'Pichi Mahuida', 'province_id' => '16'],
            ['name' => 'Pilcaniyeu', 'province_id' => '16'],
            ['name' => 'San Antonio', 'province_id' => '16'],
            ['name' => 'Valcheta', 'province_id' => '16'],
            ['name' => 'Anta', 'province_id' => '17'],
            ['name' => 'Cachi', 'province_id' => '17'],
            ['name' => 'Cafayate', 'province_id' => '17'],
            ['name' => 'Capital', 'province_id' => '17'],
            ['name' => 'Cerrillos', 'province_id' => '17'],
            ['name' => 'Chicoana', 'province_id' => '17'],
            ['name' => 'General Jose De San Martin', 'province_id' => '17'],
            ['name' => 'General Martin M Guemes', 'province_id' => '17'],
            ['name' => 'Guachipas', 'province_id' => '17'],
            ['name' => 'Iruya', 'province_id' => '17'],
            ['name' => 'La Caldera', 'province_id' => '17'],
            ['name' => 'La Candelaria', 'province_id' => '17'],
            ['name' => 'La Poma', 'province_id' => '17'],
            ['name' => 'Los Andes', 'province_id' => '17'],
            ['name' => 'Metan', 'province_id' => '17'],
            ['name' => 'Molinos', 'province_id' => '17'],
            ['name' => 'Oran', 'province_id' => '17'],
            ['name' => 'Rivadavia', 'province_id' => '17'],
            ['name' => 'Rosario De La Frontera', 'province_id' => '17'],
            ['name' => 'Rosario De Lerma', 'province_id' => '17'],
            ['name' => 'San Carlos', 'province_id' => '17'],
            ['name' => 'Santa Victoria', 'province_id' => '17'],
            ['name' => '25 De Mayo', 'province_id' => '18'],
            ['name' => '9 De Julio', 'province_id' => '18'],
            ['name' => 'Albardon', 'province_id' => '18'],
            ['name' => 'Angaco', 'province_id' => '18'],
            ['name' => 'Calingasta', 'province_id' => '18'],
            ['name' => 'Capital', 'province_id' => '18'],
            ['name' => 'Caucete', 'province_id' => '18'],
            ['name' => 'Chimbas', 'province_id' => '18'],
            ['name' => 'Iglesia', 'province_id' => '18'],
            ['name' => 'Jachal', 'province_id' => '18'],
            ['name' => 'Pocito', 'province_id' => '18'],
            ['name' => 'Rawson', 'province_id' => '18'],
            ['name' => 'Rivadavia', 'province_id' => '18'],
            ['name' => 'San Martin', 'province_id' => '18'],
            ['name' => 'Santa Lucia', 'province_id' => '18'],
            ['name' => 'Sarmiento', 'province_id' => '18'],
            ['name' => 'Ullum', 'province_id' => '18'],
            ['name' => 'Valle Fertil', 'province_id' => '18'],
            ['name' => 'Zonda', 'province_id' => '18'],
            ['name' => 'Ayacucho', 'province_id' => '19'],
            ['name' => 'Belgrano', 'province_id' => '19'],
            ['name' => 'Chacabuco', 'province_id' => '19'],
            ['name' => 'Coronel Pringles', 'province_id' => '19'],
            ['name' => 'General Pedernera', 'province_id' => '19'],
            ['name' => 'Gobernador Dupuy', 'province_id' => '19'],
            ['name' => 'Junin', 'province_id' => '19'],
            ['name' => 'La Capital', 'province_id' => '19'],
            ['name' => 'Libertador Gral San Martin', 'province_id' => '19'],
            ['name' => 'Corpen Aike', 'province_id' => '20'],
            ['name' => 'Deseado', 'province_id' => '20'],
            ['name' => 'Guer Aike', 'province_id' => '20'],
            ['name' => 'Lago Argentino', 'province_id' => '20'],
            ['name' => 'Lago Buenos Aires', 'province_id' => '20'],
            ['name' => 'Magallanes', 'province_id' => '20'],
            ['name' => '9 De Julio', 'province_id' => '21'],
            ['name' => 'Belgrano', 'province_id' => '21'],
            ['name' => 'Caseros', 'province_id' => '21'],
            ['name' => 'Castellanos', 'province_id' => '21'],
            ['name' => 'Constitucion', 'province_id' => '21'],
            ['name' => 'Garay', 'province_id' => '21'],
            ['name' => 'General Lopez', 'province_id' => '21'],
            ['name' => 'General Obligado', 'province_id' => '21'],
            ['name' => 'Iriondo', 'province_id' => '21'],
            ['name' => 'La Capital', 'province_id' => '21'],
            ['name' => 'Las Colonias', 'province_id' => '21'],
            ['name' => 'Rosario', 'province_id' => '21'],
            ['name' => 'San Cristobal', 'province_id' => '21'],
            ['name' => 'San Javier', 'province_id' => '21'],
            ['name' => 'San Jeronimo', 'province_id' => '21'],
            ['name' => 'San Justo', 'province_id' => '21'],
            ['name' => 'San Lorenzo', 'province_id' => '21'],
            ['name' => 'San Martin', 'province_id' => '21'],
            ['name' => 'Vera', 'province_id' => '21'],
            ['name' => 'Aguirre', 'province_id' => '22'],
            ['name' => 'Alberdi', 'province_id' => '22'],
            ['name' => 'Atamisqui', 'province_id' => '22'],
            ['name' => 'Avellaneda', 'province_id' => '22'],
            ['name' => 'Banda', 'province_id' => '22'],
            ['name' => 'Belgrano', 'province_id' => '22'],
            ['name' => 'Brigadier Juan F Ibarra', 'province_id' => '22'],
            ['name' => 'Capital', 'province_id' => '22'],
            ['name' => 'Choya', 'province_id' => '22'],
            ['name' => 'Copo', 'province_id' => '22'],
            ['name' => 'Figueroa', 'province_id' => '22'],
            ['name' => 'General San Martin', 'province_id' => '22'],
            ['name' => 'General Taboada', 'province_id' => '22'],
            ['name' => 'Guasayan', 'province_id' => '22'],
            ['name' => 'Jimenez', 'province_id' => '22'],
            ['name' => 'Loreto', 'province_id' => '22'],
            ['name' => 'Mitre', 'province_id' => '22'],
            ['name' => 'Moreno', 'province_id' => '22'],
            ['name' => 'Ojo De Agua', 'province_id' => '22'],
            ['name' => 'Pellegrini', 'province_id' => '22'],
            ['name' => 'Quebrachos', 'province_id' => '22'],
            ['name' => 'Rio Hondo', 'province_id' => '22'],
            ['name' => 'Rivadavia', 'province_id' => '22'],
            ['name' => 'Robles', 'province_id' => '22'],
            ['name' => 'Salavina', 'province_id' => '22'],
            ['name' => 'Sarmiento', 'province_id' => '22'],
            ['name' => 'Silipica', 'province_id' => '22'],
            ['name' => 'Antartida', 'province_id' => '23'],
            ['name' => 'Malvinas', 'province_id' => '23'],
            ['name' => 'Rio Grande', 'province_id' => '23'],
            ['name' => 'Ushuaia', 'province_id' => '23'],
            ['name' => 'Burruyacu', 'province_id' => '24'],
            ['name' => 'Capital', 'province_id' => '24'],
            ['name' => 'Chicligasta', 'province_id' => '24'],
            ['name' => 'Cruz Alta', 'province_id' => '24'],
            ['name' => 'Famailla', 'province_id' => '24'],
            ['name' => 'Graneros', 'province_id' => '24'],
            ['name' => 'Juan B Alberdi', 'province_id' => '24'],
            ['name' => 'La Cocha', 'province_id' => '24'],
            ['name' => 'Leales', 'province_id' => '24'],
            ['name' => 'Lules', 'province_id' => '24'],
            ['name' => 'Monteros', 'province_id' => '24'],
            ['name' => 'Rio Chico', 'province_id' => '24'],
            ['name' => 'Simoca', 'province_id' => '24'],
            ['name' => 'Tafi Del Valle', 'province_id' => '24'],
            ['name' => 'Tafi Viejo', 'province_id' => '24'],
            ['name' => 'Trancas', 'province_id' => '24'],
            ['name' => 'Yerba Buena', 'province_id' => '24'],
            ['name' => 'Rio Chico', 'province_id' => '20'],
        ];
        foreach ($districts as $district) {
            District::create($district);
        }
    }
}
